#!/usr/bin/env sh

# Check if correct number of arguments has been provided
if [ $# -lt 1 ]; then
    echo "  You need to provide serial port."
    echo "  Examples:"
    echo "    serial_check ttyUSB0"
    echo "    serial_check ttyS3"
    echo ""
    exit 1
fi

PID=`ps -aux | grep -e "[s]erial_open .* ${1}" | awk 'FNR == 1 {print $2}'`
if [ "$PID" ]; then
    echo "The port is open."
else
    echo "The port is closed."
fi

exit 0
